import type { DiagnosticPanel } from '@/types';

export const diagnosticPanels: DiagnosticPanel[] = [
  {
    id: 'panel_hem_dog',
    name: 'Canine Hematology',
    nameFa: 'هماتولوژی سگ',
    category: 'hematology',
    species: ['dog'],
    parameters: [
      {
        name: 'RBC',
        nameFa: 'گلبول قرمز',
        unit: 'x10^6/µL',
        unitFa: 'میلیون در میکرولیتر',
        referenceRange: { min: 5.5, max: 8.5 },
        referenceRangeFa: { min: 5.5, max: 8.5 },
        clinicalSignificance: 'Decreased in anemia, blood loss, hemolysis. Increased in dehydration, polycythemia.',
        clinicalSignificanceFa: 'کاهش در کم‌خونی، خونریزی، همولیز. افزایش در دهیدراتاسیون.',
      },
      {
        name: 'Hematocrit (HCT)',
        nameFa: 'هماتوکریت',
        unit: '%',
        unitFa: 'درصد',
        referenceRange: { min: 37, max: 55 },
        referenceRangeFa: { min: 37, max: 55 },
        clinicalSignificance: 'Key marker for anemia and hydration status. Low: anemia. High: dehydration.',
        clinicalSignificanceFa: 'نشانگر کلیدی کم‌خونی و هیدراتاسیون. پایین: کم‌خونی. بالا: دهیدراتاسیون.',
      },
      {
        name: 'WBC',
        nameFa: 'گلبول سفید',
        unit: 'x10^3/µL',
        unitFa: 'هزار در میکرولیتر',
        referenceRange: { min: 6.0, max: 17.0 },
        referenceRangeFa: { min: 6.0, max: 17.0 },
        clinicalSignificance: 'Increased in infection, inflammation, leukemia. Decreased in viral infection, bone marrow suppression.',
        clinicalSignificanceFa: 'افزایش در عفونت، التهاب، لوکمی. کاهش در عفونت ویروسی، سرکوب مغز استخوان.',
      },
      {
        name: 'Platelets',
        nameFa: 'پلاکت',
        unit: 'x10^3/µL',
        unitFa: 'هزار در میکرولیتر',
        referenceRange: { min: 200, max: 500 },
        referenceRangeFa: { min: 200, max: 500 },
        clinicalSignificance: 'Decreased in thrombocytopenia (immune-mediated, tick-borne, DIC). Critical if <30K: bleeding risk.',
        clinicalSignificanceFa: 'کاهش در ترومبوسیتوپنی (ایمنی، کنه‌محور، DIC). بحرانی اگر <۳۰هزار.',
      },
    ],
  },
  {
    id: 'panel_hem_cat',
    name: 'Feline Hematology',
    nameFa: 'هماتولوژی گربه',
    category: 'hematology',
    species: ['cat'],
    parameters: [
      {
        name: 'RBC',
        nameFa: 'گلبول قرمز',
        unit: 'x10^6/µL',
        unitFa: 'میلیون در میکرولیتر',
        referenceRange: { min: 5.0, max: 10.0 },
        referenceRangeFa: { min: 5.0, max: 10.0 },
        clinicalSignificance: 'Decreased in anemia. Cats prone to Heinz body formation with toxins.',
        clinicalSignificanceFa: 'کاهش در کم‌خونی. گربه‌ها مستعد تشکیل بادی هاینز با سموم.',
      },
      {
        name: 'Hematocrit (HCT)',
        nameFa: 'هماتوکریت',
        unit: '%',
        unitFa: 'درصد',
        referenceRange: { min: 30, max: 45 },
        referenceRangeFa: { min: 30, max: 45 },
        clinicalSignificance: 'Lower range than dogs. Critical if <15%: transfusion may be needed.',
        clinicalSignificanceFa: 'بازه پایین‌تر از سگ. بحرانی اگر <۱۵٪: تزریق خون ممکن است لازم باشد.',
      },
      {
        name: 'WBC',
        nameFa: 'گلبول سفید',
        unit: 'x10^3/µL',
        unitFa: 'هزار در میکرولیتر',
        referenceRange: { min: 5.5, max: 19.5 },
        referenceRangeFa: { min: 5.5, max: 19.5 },
        clinicalSignificance: 'Cats have wider WBC range. Stress leukogram common in cats.',
        clinicalSignificanceFa: 'گربه‌ها بازه وسیع‌تری دارند. لوکوگرام استرس شایع است.',
      },
      {
        name: 'Platelets',
        nameFa: 'پلاکت',
        unit: 'x10^3/µL',
        unitFa: 'هزار در میکرولیتر',
        referenceRange: { min: 300, max: 700 },
        referenceRangeFa: { min: 300, max: 700 },
        clinicalSignificance: 'Higher range than dogs. Platelet clumping common in cats (may falsely lower count).',
        clinicalSignificanceFa: 'بازه بالاتر از سگ. تجمع پلاکتی شایع است (ممکن است کاذب پایین بیاید).',
      },
    ],
  },
  {
    id: 'panel_chem_dog',
    name: 'Canine Biochemistry',
    nameFa: 'بیوشیمی سگ',
    category: 'biochemistry',
    species: ['dog'],
    parameters: [
      {
        name: 'ALT',
        nameFa: 'آلانین آمینوترانسفراز',
        unit: 'U/L',
        unitFa: 'واحد در لیتر',
        referenceRange: { min: 10, max: 125 },
        referenceRangeFa: { min: 10, max: 125 },
        clinicalSignificance: 'Liver-specific enzyme. Elevated in hepatocellular damage, hepatitis, drug toxicity, hepatic neoplasia.',
        clinicalSignificanceFa: 'آنزیم اختصاصی کبد. افزایش در آسیت هپاتوسلولی، هپاتیت، سمیت دارویی.',
      },
      {
        name: 'ALP',
        nameFa: 'آلکالین فسفاتاز',
        unit: 'U/L',
        unitFa: 'واحد در لیتر',
        referenceRange: { min: 23, max: 212 },
        referenceRangeFa: { min: 23, max: 212 },
        clinicalSignificance: 'Elevated in cholestasis, bone disease, Cushing\'s disease, growing dogs. Less liver-specific than ALT.',
        clinicalSignificanceFa: 'افزایش در کلستاز، بیماری استخوانی، کوشینگ، سگ‌های در حال رشد.',
      },
      {
        name: 'BUN',
        nameFa: 'ازوت اوره خون',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 7, max: 27 },
        referenceRangeFa: { min: 7, max: 27 },
        clinicalSignificance: 'Elevated in renal disease, dehydration, GI bleeding, high protein diet. Decreased in liver failure.',
        clinicalSignificanceFa: 'افزایش در بیماری کلیوی، دهیدراتاسیون، خونریزی گوارش. کاهش در نارسایی کبد.',
      },
      {
        name: 'Creatinine',
        nameFa: 'کراتینین',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 0.4, max: 1.8 },
        referenceRangeFa: { min: 0.4, max: 1.8 },
        clinicalSignificance: 'More specific for renal function than BUN. Elevated in acute/chronic kidney disease. Check with SDMA for early detection.',
        clinicalSignificanceFa: 'اختصاصی‌تر از BUN برای عملکرد کلیوی. افزایش در بیماری حاد/مزمن کلیوی.',
      },
      {
        name: 'Glucose',
        nameFa: 'گلوکز',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 70, max: 143 },
        referenceRangeFa: { min: 70, max: 143 },
        clinicalSignificance: 'Elevated in diabetes mellitus, stress (cats), Cushing\'s. Decreased in insulinoma, sepsis, Addison\'s.',
        clinicalSignificanceFa: 'افزایش در دیابت، استرس (گربه)، کوشینگ. کاهش در اینسولینوما، سپسیس.',
      },
    ],
  },
  {
    id: 'panel_chem_cat',
    name: 'Feline Biochemistry',
    nameFa: 'بیوشیمی گربه',
    category: 'biochemistry',
    species: ['cat'],
    parameters: [
      {
        name: 'ALT',
        nameFa: 'آلانین آمینوترانسفراز',
        unit: 'U/L',
        unitFa: 'واحد در لیتر',
        referenceRange: { min: 10, max: 100 },
        referenceRangeFa: { min: 10, max: 100 },
        clinicalSignificance: 'Liver enzyme. Elevated in hepatic lipidosis, cholangiohepatitis, toxin exposure.',
        clinicalSignificanceFa: 'آنزیم کبدی. افزایش در لیپیدوز کبدی، کلانژیوهپاتیت، مواجهه با سم.',
      },
      {
        name: 'BUN',
        nameFa: 'ازوت اوره خون',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 15, max: 35 },
        referenceRangeFa: { min: 15, max: 35 },
        clinicalSignificance: 'Cats have higher baseline BUN. Elevated in renal disease (common in older cats), dehydration.',
        clinicalSignificanceFa: 'گربه‌ها BUN پایه بالاتری دارند. افزایش در بیماری کلیوی (شایع در گربه مسن).',
      },
      {
        name: 'Creatinine',
        nameFa: 'کراتینین',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 0.8, max: 2.3 },
        referenceRangeFa: { min: 0.8, max: 2.3 },
        clinicalSignificance: 'Key renal marker in cats. CKD is extremely common in older cats. Monitor trends over time.',
        clinicalSignificanceFa: 'نشانگر کلیدی کلیوی در گربه. CKD بسیار شایع در گربه‌های مسن.',
      },
      {
        name: 'Glucose',
        nameFa: 'گلوکز',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 60, max: 160 },
        referenceRangeFa: { min: 60, max: 160 },
        clinicalSignificance: 'Cats are prone to stress hyperglycemia. Confirm diabetes with fructosamine if glucose is high.',
        clinicalSignificanceFa: 'گربه‌ها مستعد هایپرگلیسمی استرسی. دیابت را با فروکتوزامین تأیید کنید.',
      },
      {
        name: 'Total T4',
        nameFa: 'تیروکسین کل',
        unit: 'µg/dL',
        unitFa: 'میکروگرم در دسی‌لیتر',
        referenceRange: { min: 1.0, max: 4.0 },
        referenceRangeFa: { min: 1.0, max: 4.0 },
        clinicalSignificance: 'Elevated in hyperthyroidism (common in older cats >8 years). Check if weight loss + polyphagia.',
        clinicalSignificanceFa: 'افزایش در پرکاری تیروئید (شایع در گربه‌های >۸ سال).',
      },
    ],
  },
  {
    id: 'panel_elect_dog',
    name: 'Canine Electrolytes',
    nameFa: 'الکترولیت‌های سگ',
    category: 'electrolytes',
    species: ['dog'],
    parameters: [
      {
        name: 'Sodium',
        nameFa: 'سدیم',
        unit: 'mmol/L',
        unitFa: 'میلی‌مول در لیتر',
        referenceRange: { min: 139, max: 154 },
        referenceRangeFa: { min: 139, max: 154 },
        clinicalSignificance: 'Low: Addison\'s disease, GI loss, diuretics. High: dehydration, diabetes insipidus, salt toxicity.',
        clinicalSignificanceFa: 'پایین: آدیسون، فقدان گوارشی، دیورتیک. بالا: دهیدراتاسیون، دیابت ملیتوس.',
      },
      {
        name: 'Potassium',
        nameFa: 'پتاسیم',
        unit: 'mmol/L',
        unitFa: 'میلی‌مول در لیتر',
        referenceRange: { min: 3.8, max: 5.6 },
        referenceRangeFa: { min: 3.8, max: 5.6 },
        clinicalSignificance: 'Low: vomiting/diarrhea, diuretics. High: Addison\'s, renal failure, urinary obstruction. Critical: cardiac arrhythmia.',
        clinicalSignificanceFa: 'پایین: استفراغ/اسهال، دیورتیک. بالا: آدیسون، نارسایی کلیوی. بحرانی: آریتمی قلبی.',
      },
      {
        name: 'Chloride',
        nameFa: 'کلر',
        unit: 'mmol/L',
        unitFa: 'میلی‌مول در لیتر',
        referenceRange: { min: 102, max: 120 },
        referenceRangeFa: { min: 102, max: 120 },
        clinicalSignificance: 'Generally follows sodium. Low chloride with high sodium suggests Addison\'s.',
        clinicalSignificanceFa: 'عموماً همراه سدیم. کلر پایین با سدیم بالا نشانگر آدیسون.',
      },
    ],
  },
  {
    id: 'panel_hem_horse',
    name: 'Equine Hematology',
    nameFa: 'هماتولوژی اسب',
    category: 'hematology',
    species: ['horse'],
    parameters: [
      {
        name: 'RBC',
        nameFa: 'گلبول قرمز',
        unit: 'x10^6/µL',
        unitFa: 'میلیون در میکرولیتر',
        referenceRange: { min: 6.5, max: 11.0 },
        referenceRangeFa: { min: 6.5, max: 11.0 },
        clinicalSignificance: 'Spleen can release RBCs with excitement — resting sample important. Decreased in anemia, blood loss.',
        clinicalSignificanceFa: 'طحال با هیجان گلبول قرمز آزاد می‌کند — نمونه استراحت مهم است.',
      },
      {
        name: 'WBC',
        nameFa: 'گلبول سفید',
        unit: 'x10^3/µL',
        unitFa: 'هزار در میکرولیتر',
        referenceRange: { min: 5.0, max: 11.0 },
        referenceRangeFa: { min: 5.0, max: 11.0 },
        clinicalSignificance: 'Elevated in infection (common: respiratory, GI). Mild elevations with stress/excitement.',
        clinicalSignificanceFa: 'افزایش در عفونت (تنفسی، گوارشی). افزایش خفیف با استرس.',
      },
      {
        name: 'Fibrinogen',
        nameFa: 'فیبرینوژن',
        unit: 'mg/dL',
        unitFa: 'میلی‌گرم در دسی‌لیتر',
        referenceRange: { min: 100, max: 400 },
        referenceRangeFa: { min: 100, max: 400 },
        clinicalSignificance: 'Key inflammatory marker in horses. Elevated in infection, inflammation. More reliable than WBC alone.',
        clinicalSignificanceFa: 'نشانگر التهابی کلیدی در اسب. افزایش در عفونت، التهاب.',
      },
    ],
  },
];
