import type { Disease } from '@/types';

export const diseases: Disease[] = [
  {
    id: 'canine_distemper',
    name: 'Canine Distemper',
    nameFa: 'دیستمپر سگ‌ها',
    species: ['dog'],
    category: 'Infectious — Respiratory/Neurological',
    categoryFa: 'عفونی — تنفسی/عصبی',
    description: 'A highly contagious viral disease affecting respiratory, GI, and neurological systems.',
    descriptionFa: 'بیماری ویروسی به‌شدت مسری که سیستم تنفسی، گوارشی و عصبی را درگیر می‌کند.',
    associatedFacts: ['fever', 'cough', 'nasal_discharge', 'ocular_discharge', 'lethargy', 'anorexia', 'seizures', 'ataxia', 'vaccination_incomplete', 'unvaccinated', 'young_age', 'leukopenia'],
  },
  {
    id: 'canine_parvovirus',
    name: 'Canine Parvovirus',
    nameFa: 'پاروویروس سگ‌ها',
    species: ['dog'],
    category: 'Infectious — Gastrointestinal',
    categoryFa: 'عفونی — گوارشی',
    description: 'A highly contagious viral disease causing severe hemorrhagic gastroenteritis, especially in puppies.',
    descriptionFa: 'بیماری ویروسی مسری که باعث گاستروانتریت هموراژیک شدید می‌شود، به‌ویژه در سگ‌های جوان.',
    associatedFacts: ['vomiting', 'bloody_diarrhea', 'lethargy', 'anorexia', 'fever', 'dehydration', 'abdominal_pain', 'unvaccinated', 'vaccination_incomplete', 'young_age', 'leukopenia'],
    redFlag: true,
  },
  {
    id: 'kennel_cough',
    name: 'Infectious Tracheobronchitis (Kennel Cough)',
    nameFa: 'سرفه‌ی لانه‌ای (Kennel Cough)',
    species: ['dog'],
    category: 'Infectious — Respiratory',
    categoryFa: 'عفونی — تنفسی',
    description: 'A highly contagious respiratory disease complex causing persistent dry cough.',
    descriptionFa: 'بیماری مسری تنفسی که باعث سرفه خشک و مداوم می‌شود.',
    associatedFacts: ['dry_cough', 'sneezing', 'nasal_discharge', 'recent_boarding', 'multi_pet_household', 'lethargy', 'fever'],
  },
  {
    id: 'canine_influenza',
    name: 'Canine Influenza',
    nameFa: 'آنفلوانزای سگ‌ها',
    species: ['dog'],
    category: 'Infectious — Respiratory',
    categoryFa: 'عفونی — تنفسی',
    description: 'A contagious respiratory disease caused by influenza A virus.',
    descriptionFa: 'بیماری مسری تنفسی ناشی از ویروس آنفلوانزای A.',
    associatedFacts: ['cough', 'fever', 'nasal_discharge', 'lethargy', 'anorexia', 'recent_boarding', 'multi_pet_household', 'moist_cough'],
  },
  {
    id: 'feline_panleukopenia',
    name: 'Feline Panleukopenia',
    nameFa: 'پانلوکوپنی گربه‌ها',
    species: ['cat'],
    category: 'Infectious — Gastrointestinal',
    categoryFa: 'عفونی — گوارشی',
    description: 'A highly contagious viral disease causing severe GI signs and leukopenia in cats.',
    descriptionFa: 'بیماری ویروسی مسری که علائم شدید گوارشی و کاهش گلبول سفید در گربه‌ها ایجاد می‌کند.',
    associatedFacts: ['vomiting', 'diarrhea', 'bloody_diarrhea', 'fever', 'lethargy', 'anorexia', 'dehydration', 'unvaccinated', 'vaccination_incomplete', 'young_age', 'leukopenia'],
    redFlag: true,
  },
  {
    id: 'feline_uri',
    name: 'Feline Upper Respiratory Infection (URI)',
    nameFa: 'عفونت تنفسی فوقانی گربه‌ها',
    species: ['cat'],
    category: 'Infectious — Respiratory',
    categoryFa: 'عفونی — تنفسی',
    description: 'A common contagious respiratory complex in cats (herpesvirus, calicivirus).',
    descriptionFa: 'عفونت تنفلی مسری شایع در گربه‌ها (ویروس هرپس، کالسی‌ویروس).',
    associatedFacts: ['sneezing', 'nasal_discharge', 'ocular_discharge', 'conjunctivitis', 'fever', 'lethargy', 'anorexia', 'recent_boarding', 'multi_pet_household', 'unvaccinated'],
  },
  {
    id: 'feline_ud',
    name: 'Feline Urinary Tract Disease (FLUTD)',
    nameFa: 'بیماری مجاری ادراری گربه‌ها (FLUTD)',
    species: ['cat'],
    category: 'Urological',
    categoryFa: 'ادراری',
    description: 'A syndrome causing lower urinary tract signs in cats; urinary blockage in males is an emergency.',
    descriptionFa: 'سندرمی که علائم مجاری ادراری تحتانی در گربه‌ها ایجاد می‌کند؛ انسداد در گربه‌های نر اورژانس است.',
    associatedFacts: ['stranguria', 'hematuria', 'urinary_blockage', 'vocalization', 'frequent_urination', 'abdominal_pain'],
    redFlag: true,
  },
  {
    id: 'gdv',
    name: 'Gastric Dilatation-Volvulus (GDV)',
    nameFa: 'پیچ‌خوردگی معده (GDV)',
    species: ['dog'],
    category: 'Gastrointestinal — Emergency',
    categoryFa: 'گوارشی — اورژانس',
    description: 'A life-threatening condition where the stomach twists on its axis.',
    descriptionFa: 'وضعیت خطرناک که در آن معده دور محور خود می‌چرخد.',
    associatedFacts: ['bloating', 'vomiting', 'lethargy', 'abdominal_pain', 'weak_pulse', 'anorexia', 'not_neutered'],
    redFlag: true,
  },
  {
    id: 'flea_allergy_dermatitis',
    name: 'Flea Allergy Dermatitis',
    nameFa: 'درماشیت آلرژیک به کک',
    species: ['dog', 'cat'],
    category: 'Dermatological',
    categoryFa: 'پوستی',
    description: 'An allergic reaction to flea saliva causing intense itching and skin inflammation.',
    descriptionFa: 'واکنش آلرژیک به بزاق کک که خارش شدید و التهاب پوست ایجاد می‌کند.',
    associatedFacts: ['pruritus', 'alopecia', 'erythema', 'skin_lesions', 'flea_dirt', 'otitis'],
  },
  {
    id: 'sarcoptic_mange',
    name: 'Sarcoptic Mange',
    nameFa: 'گَرد سارکوپتیک',
    species: ['dog'],
    category: 'Dermatological — Parasitic',
    categoryFa: 'پوستی — انگلی',
    description: 'A contagious skin disease caused by Sarcoptes scabiei mites.',
    descriptionFa: 'بیماری مسری پوستی ناشی از کنه سارکوپتیکس اسکابی‌ای.',
    associatedFacts: ['pruritus', 'alopecia', 'skin_lesions', 'mange_lesions', 'erythema', 'outdoor_access'],
  },
  {
    id: 'tick_borne_disease',
    name: 'Tick-Borne Disease (Ehrlichiosis/Anaplasmosis)',
    nameFa: 'بیماری‌های منتقله از کنه',
    species: ['dog'],
    category: 'Infectious — Vector-borne',
    categoryFa: 'عفونی — ناقل',
    description: 'Infections transmitted by ticks causing fever, lethargy, and hematological abnormalities.',
    descriptionFa: 'عفونت‌های منتقله توسط کنه که باعث تب، بی‌حالی و اختلالات خونی می‌شوند.',
    associatedFacts: ['fever', 'lethargy', 'anorexia', 'lameness', 'joint_swelling', 'lymphadenopathy', 'tick_exposure', 'thrombocytopenia', 'anemia', 'pale_mucous_membranes'],
  },
  {
    id: 'diabetes_mellitus',
    name: 'Diabetes Mellitus',
    nameFa: 'دیابت شیرین',
    species: ['dog', 'cat'],
    category: 'Endocrine',
    categoryFa: 'غدد',
    description: 'A metabolic disorder causing elevated blood sugar, PU/PD, and weight changes.',
    descriptionFa: 'اختلال متابولیک که باعث افزایش قند خون، تکرر ادرار و تشنگی می‌شود.',
    associatedFacts: ['polyuria', 'polydipsia', 'weight_loss', 'anorexia', 'lethargy', 'elevated_liver_enzymes'],
  },
  {
    id: 'chronic_kidney_disease',
    name: 'Chronic Kidney Disease',
    nameFa: 'بیماری مزمن کلیه',
    species: ['cat', 'dog'],
    category: 'Renal',
    categoryFa: 'کلیوی',
    description: 'Progressive loss of kidney function causing PU/PD, anorexia, and azotemia.',
    descriptionFa: 'از دست رفتن پیشرونده عملکرد کلیه که باعث تکرر ادرار، بی‌اشتهایی و ازتمی می‌شود.',
    associatedFacts: ['polyuria', 'polydipsia', 'anorexia', 'weight_loss', 'vomiting', 'lethargy', 'dehydration', 'azotemia', 'pale_mucous_membranes'],
  },
  {
    id: 'hepatic_disease',
    name: 'Hepatic Disease',
    nameFa: 'بیماری کبدی',
    species: ['dog', 'cat'],
    category: 'Hepatobiliary',
    categoryFa: 'کبدی-صفراوی',
    description: 'Liver dysfunction causing jaundice, GI signs, and altered mentation.',
    descriptionFa: 'اختلال عملکرد کبد که باعث یرقان، علائم گوارشی و تغییر هوشیاری می‌شود.',
    associatedFacts: ['jaundice', 'vomiting', 'anorexia', 'lethargy', 'elevated_liver_enzymes', 'altered_mentation', 'weight_loss', 'polyuria', 'polydipsia'],
  },
  {
    id: 'intoxication',
    name: 'Intoxication / Toxicity',
    nameFa: 'مسمومیت',
    species: ['dog', 'cat'],
    category: 'Toxicological — Emergency',
    categoryFa: 'مسمومیت — اورژانس',
    description: 'Ingestion or exposure to toxins causing varied clinical signs.',
    descriptionFa: 'مصرف یا تماس با مواد سمی که علائم بالینی متنوعی ایجاد می‌کند.',
    associatedFacts: ['vomiting', 'diarrhea', 'seizures', 'ataxia', 'lethargy', 'toxin_exposure', 'salivation', 'tremors', 'altered_mentation'],
    redFlag: true,
  },
  {
    id: 'chf',
    name: 'Congestive Heart Failure',
    nameFa: 'نارسایی احتقانی قلب',
    species: ['dog', 'cat'],
    category: 'Cardiovascular',
    categoryFa: 'قلبی-عروقی',
    description: 'Heart dysfunction causing fluid accumulation, cough, and exercise intolerance.',
    descriptionFa: 'اختلال قلب که باعث تجمع مایعات، سرفه و عدم تحمل فعالیت می‌شود.',
    associatedFacts: ['cough', 'cough_on_exertion', 'exercise_intolerance', 'respiratory_distress', 'lethargy', 'syncope', 'weak_pulse', 'dyspnea'],
  },
  {
    id: 'ivdd',
    name: 'Intervertebral Disc Disease (IVDD)',
    nameFa: 'بیماری دیسک بین‌مهره‌ای',
    species: ['dog'],
    category: 'Neurological / Musculoskeletal',
    categoryFa: 'عصبی / عضلانی-اسکلتی',
    description: 'Disc herniation causing back pain, paresis, or paralysis.',
    descriptionFa: 'فتق دیسک که باعث درد کمر، ضعف یا فلجی می‌شود.',
    associatedFacts: ['back_pain', 'paresis', 'paralysis', 'ataxia', 'lameness', 'lethargy'],
  },
];
