import type { DrugInfo } from '@/types';

export const drugDatabase: DrugInfo[] = [
  {
    id: 'drug_amoxicillin',
    genericName: 'Amoxicillin',
    genericNameFa: 'آموکسی‌سیلین',
    drugClass: 'Beta-lactam antibiotic (aminopenicillin)',
    drugClassFa: 'آنتی‌بیوتیک بتا-لاکتام',
    species: ['dog', 'cat', 'horse', 'cattle', 'sheep', 'goat', 'bird', 'rabbit', 'other'],
    indication: 'Broad-spectrum bacterial infections: skin, respiratory, urinary, soft tissue',
    indicationFa: 'عفونت‌های باکتریایی وسیع‌الطیف: پوستی، تنفسی، ادراری، بافت نرم',
    mechanism: 'Inhibits bacterial cell wall synthesis by binding to PBPs, causing cell lysis.',
    mechanismFa: 'مهار سنتز دیواره سلولی باکتری با اتصال به PBP، باعث لیز سلولی می‌شود.',
    doseMgPerKg: '10-20 mg/kg',
    route: 'PO (oral)',
    routeFa: 'خوراکی',
    frequency: 'BID (twice daily)',
    frequencyFa: 'دو بار در روز',
    duration: '5-7 days (extend per clinical response)',
    durationFa: '۵-۷ روز (بسته به پاسخ بالینی)',
    contraindications: 'Hypersensitivity to penicillins. Use with caution in rodents/rabbits.',
    contraindicationsFa: 'حساسیت به پنی‌سیلین‌ها. با احتیاط در جوندگان.',
    adverseEffects: 'GI upset, diarrhea, allergic reactions. Rare: anaphylaxis.',
    adverseEffectsFa: 'اختلال گوارش، اسهال، واکنش‌های آلرژیک. نادر: آنافیلاکسی.',
    interactions: 'May reduce effectiveness of oral contraceptives. Synergistic with aminoglycosides.',
    interactionsFa: 'کاهش اثر ضدبارداری‌های خوراکی. هم‌افزایی با آمینوگلیکوزیدها.',
    monitoring: 'Monitor for GI signs and allergic reactions. Check clinical response at 48-72h.',
    monitoringFa: 'پایش علائم گوارشی و آلرژیک. بررسی پاسخ بالینی در ۴۸-۷۲ ساعت.',
    withdrawalPeriod: 'Cattle: 25 days (meat), 48h (milk). Sheep: 14 days (meat).',
    withdrawalPeriodFa: 'گاو: ۲۵ روز (گوشت)، ۴۸ ساعت (شیر). گوسفند: ۱۴ روز (گوشت).',
    specialPopulations: 'Reduce dose in severe renal impairment. Safe in pregnancy (category B).',
    specialPopulationsFa: 'کاهش دوز در نارسایی شدید کلیوی. ایمن در بارداری.',
    evidenceLevel: 'strong',
  },
  {
    id: 'drug_enrofloxacin',
    genericName: 'Enrofloxacin',
    genericNameFa: 'آنروفلوکساسین',
    drugClass: 'Fluoroquinolone antibiotic',
    drugClassFa: 'آنتی‌بیوتیک فلوروکینولون',
    species: ['dog', 'cat', 'horse', 'cattle', 'other'],
    indication: 'Gram-negative infections, skin, urinary tract, respiratory, prostatitis',
    indicationFa: 'عفونت‌های گرم-منفی، پوستی، ادراری، تنفسی، پروستاتیت',
    mechanism: 'Inhibits bacterial DNA gyrase and topoisomerase IV, preventing DNA replication.',
    mechanismFa: 'مهار DNA گیراز و توپوایزومراز IV، جلوگیری از تکثیر DNA.',
    doseMgPerKg: '5-20 mg/kg',
    route: 'PO, SC, IM',
    routeFa: 'خوراکی، زیرجلدی، عضلانی',
    frequency: 'SID (once daily)',
    frequencyFa: 'یک بار در روز',
    duration: '5-14 days (varies by infection)',
    durationFa: '۵-۱۴ روز (بسته به عفونت)',
    contraindications: 'Young growing animals (cartilage damage). Pregnancy. History of seizures.',
    contraindicationsFa: 'حیوانات جوان در حال رشد (آسیب غضروف). بارداری. سابقه تشنج.',
    adverseEffects: 'Cartilage damage in young animals, GI upset, seizures (cats), retinal degeneration (cats - rare).',
    adverseEffectsFa: 'آسیب غضروف در حیوانات جوان، اختلال گوارش، تشنج (گربه)، دژنراسیون شبکیه (نادر).',
    interactions: 'Antacids reduce absorption. NSAIDs may increase seizure risk. Theophylline levels increase.',
    interactionsFa: 'آنتی‌اسیدها جذب را کاهش می‌دهند. NSAIDها خطر تشنج را افزایش می‌دهند.',
    monitoring: 'Monitor for GI signs, neurological signs, and cartilage issues in young animals.',
    monitoringFa: 'پایش علائم گوارشی، عصبی، و غضروفی در حیوانات جوان.',
    withdrawalPeriod: 'Cattle: 28 days (meat). Not approved for dairy cattle in some regions.',
    withdrawalPeriodFa: 'گاو: ۲۸ روز (گوشت). در برخی مناطق برای گاو شیری تأیید نشده.',
    specialPopulations: 'Avoid in puppies <8 months (large breeds <18 months) and kittens <8 weeks.',
    specialPopulationsFa: 'اجتناب از توله‌سگ‌های <۸ ماه (نژاد بزرگ <۱۸ ماه) و گربه‌چه‌های <۸ هفته.',
    evidenceLevel: 'strong',
  },
  {
    id: 'drug_metronidazole',
    genericName: 'Metronidazole',
    genericNameFa: 'مترونیدازول',
    drugClass: 'Nitroimidazole antibiotic/antiprotozoal',
    drugClassFa: 'آنتی‌بیوتیک/ضدتک‌یاخته نیتروایمیدازول',
    species: ['dog', 'cat', 'horse', 'other'],
    indication: 'Anaerobic infections, Giardia, inflammatory bowel disease, periodontal disease',
    indicationFa: 'عفونت‌های بی‌هوازی، ژیاردیا، بیماری التهابی روده، بیماری پریودنتال',
    mechanism: 'Disrupts DNA structure and inhibits nucleic acid synthesis in anaerobes.',
    mechanismFa: 'تخریب ساختار DNA و مهار سنتز اسید نوکلئیک در باکتری‌های بی‌هوازی.',
    doseMgPerKg: '10-30 mg/kg',
    route: 'PO, IV',
    routeFa: 'خوراکی، وریدی',
    frequency: 'BID (twice daily)',
    frequencyFa: 'دو بار در روز',
    duration: '5-7 days (Giardia: 5 days; IBD: longer courses)',
    durationFa: '۵-۷ روز (ژیاردیا: ۵ روز؛ IBD: طولانی‌تر)',
    contraindications: 'First trimester pregnancy. Liver disease (dose adjust). CNS disorders.',
    contraindicationsFa: 'سه‌ماهه اول بارداری. بیماری کبدی (تنظیم دوز). اختلالات CNS.',
    adverseEffects: 'Neurotoxicity (ataxia, nystagmus, seizures), GI upset, dark urine, metallic taste.',
    adverseEffectsFa: 'سمیت عصبی (آتاکسی، نیستاگموس، تشنج)، اختلال گوارش، طعم فلزی.',
    interactions: 'Warfarin: increased anticoagulant effect. Alcohol: disulfiram-like reaction. Phenobarbital: reduces levels.',
    interactionsFa: 'وارفارین: افزایش اثر ضدانعقاد. الکل: واکنش دی‌سولفیرام‌مانند.',
    monitoring: 'Monitor for neurological signs (especially at high doses or prolonged use).',
    monitoringFa: 'پایش علائم عصبی (مخصوصاً در دوز بالا یا مصرف طولانی).',
    withdrawalPeriod: null,
    withdrawalPeriodFa: null,
    specialPopulations: 'Reduce dose in hepatic impairment. Caution in pregnant animals.',
    specialPopulationsFa: 'کاهش دوز در اختلال کبدی. احتیاط در حیوانات باردار.',
    evidenceLevel: 'strong',
  },
  {
    id: 'drug_meloxicam',
    genericName: 'Meloxicam',
    genericNameFa: 'ملوکسیکام',
    drugClass: 'NSAID (COX-2 preferential)',
    drugClassFa: 'NSAID (ترجیحی COX-2)',
    species: ['dog', 'cat', 'horse', 'cattle', 'sheep', 'goat'],
    indication: 'Pain and inflammation: osteoarthritis, post-surgical, musculoskeletal',
    indicationFa: 'درد و التهاب: استئوآرتریت، بعد از جراحی، اسکلتی-عضلانی',
    mechanism: 'Inhibits cyclooxygenase (preferentially COX-2), reducing prostaglandin synthesis.',
    mechanismFa: 'مهار سیکلوکسیژناز (ترجیحاً COX-2)، کاهش سنتز پروستاگلاندین.',
    doseMgPerKg: '0.1-0.2 mg/kg (loading), then 0.05-0.1 mg/kg',
    route: 'PO, SC, IV',
    routeFa: 'خوراکی، زیرجلدی، وریدی',
    frequency: 'SID (once daily)',
    frequencyFa: 'یک بار در روز',
    duration: 'Varies (acute: 3-7 days; chronic OA: long-term with monitoring)',
    durationFa: 'متغیر (حاد: ۳-۷ روز؛ مزمن: بلندمدت با پایش)',
    contraindications: 'Renal impairment, GI ulceration, bleeding disorders, concurrent NSAID/corticosteroid use.',
    contraindicationsFa: 'اختلال کلیوی، زخم گوارشی، اختلالات خونریزی، مصرف همزمان NSAID/کورتیکواستروئید.',
    adverseEffects: 'GI ulceration, renal toxicity, hepatic toxicity (rare). Cats more sensitive to renal effects.',
    adverseEffectsFa: 'زخم گوارشی، سمیت کلیوی، سمیت کبدی (نادر). گربه‌ها به اثرات کلیوی حساس‌تر.',
    interactions: 'Other NSAIDs, corticosteroids, ACE inhibitors, diuretics, anticoagulants.',
    interactionsFa: 'سایر NSAIDها، کورتیکواستروئیدها، مهارکننده‌های ACE، دیورتیک‌ها.',
    monitoring: 'Baseline and periodic renal panel, liver enzymes. Monitor for GI signs.',
    monitoringFa: 'پایه و دوره‌ای پانل کلیوی، آنزیم‌های کبدی. پایش علائم گوارشی.',
    withdrawalPeriod: 'Cattle: 15 days (meat), 5 days (milk). Horse: not for food-producing use.',
    withdrawalPeriodFa: 'گاو: ۱۵ روز (گوشت)، ۵ روز (شیر). اسب: برای مصرف غذایی نیست.',
    specialPopulations: 'Use lowest effective dose in cats and elderly animals. Ensure adequate hydration.',
    specialPopulationsFa: 'کمترین دوز مؤثر در گربه‌ها و حیوانات مسن. تأمین هیدراتاسیون کافی.',
    evidenceLevel: 'strong',
  },
  {
    id: 'drug_omeprazole',
    genericName: 'Omeprazole',
    genericNameFa: 'امپرازول',
    drugClass: 'Proton pump inhibitor',
    drugClassFa: 'مهارکننده پمپ پروتون',
    species: ['dog', 'cat', 'horse', 'other'],
    indication: 'Gastric ulcers, esophagitis, GERD, prevention of NSAID-induced ulcers',
    indicationFa: 'زخم معده، التهاب مری، رفلاکس، پیشگیری از زخم ناشی از NSAID',
    mechanism: 'Irreversibly inhibits H+/K+ ATPase in gastric parietal cells, reducing acid secretion.',
    mechanismFa: 'مهار غیرقابل‌برگشت H+/K+ ATPase در سلول‌های پاریتال معده، کاهش ترشح اسید.',
    doseMgPerKg: '0.5-1.0 mg/kg (dogs/cats); 1-4 mg/kg (horses)',
    route: 'PO',
    routeFa: 'خوراکی',
    frequency: 'SID (once daily)',
    frequencyFa: 'یک بار در روز',
    duration: '14-28 days (ulcer healing); longer for chronic management',
    durationFa: '۱۴-۲۸ روز (ترمیم زخم)؛ طولانی‌تر برای مدیریت مزمن',
    contraindications: 'Hypersensitivity. Use with caution with liver disease.',
    contraindicationsFa: 'حساسیت. با احتیاط در بیماری کبدی.',
    adverseEffects: 'Generally well-tolerated. Rare: GI upset, decreased B12 absorption with long-term use.',
    adverseEffectsFa: 'عموماً تحمل‌پذیر. نادر: اختلال گوارش، کاهش جذب B12 در مصرف طولانی.',
    interactions: 'May increase levels of drugs metabolized by CYP2C19 (diazepam, phenytoin).',
    interactionsFa: 'افزایش سطح داروهای متابولیزه‌شده توسط CYP2C19.',
    monitoring: 'Monitor clinical signs of underlying condition. Long-term: consider B12 levels.',
    monitoringFa: 'پایش علائم بالینی بیماری زمینه‌ای. بلندمدت: بررسی B12.',
    withdrawalPeriod: null,
    withdrawalPeriodFa: null,
    specialPopulations: 'Generally safe in pregnancy. Dose adjust in severe hepatic disease.',
    specialPopulationsFa: 'عموماً ایمن در بارداری. تنظیم دوز در بیماری کبدی شدید.',
    evidenceLevel: 'moderate',
  },
  {
    id: 'drug_doxycycline',
    genericName: 'Doxycycline',
    genericNameFa: 'دوکسی‌سیکلین',
    drugClass: 'Tetracycline antibiotic',
    drugClassFa: 'آنتی‌بیوتیک تتراسایکلین',
    species: ['dog', 'cat', 'horse', 'bird', 'other'],
    indication: 'Tick-borne diseases (Ehrlichia, Anaplasma, Lyme), respiratory infections, Chlamydia, Mycoplasma',
    indicationFa: 'بیماری‌های کنه‌محور (ارهلیا، آناپلاسما، لایم)، عفونت‌های تنفسی، کلامیدیا',
    mechanism: 'Inhibits protein synthesis by binding to 30S ribosomal subunit.',
    mechanismFa: 'مهار سنتز پروتئین با اتصال به زیرواحد 30S ریبوزوم.',
    doseMgPerKg: '5-10 mg/kg',
    route: 'PO',
    routeFa: 'خوراکی',
    frequency: 'BID (twice daily)',
    frequencyFa: 'دو بار در روز',
    duration: '7-28 days (tick-borne: 28 days; respiratory: 7-10 days)',
    durationFa: '۷-۲۸ روز (کنه‌محور: ۲۸ روز؛ تنفسی: ۷-۱۰ روز)',
    contraindications: 'Pregnancy (tooth discoloration). Young animals <4 months. Severe liver disease.',
    contraindicationsFa: 'بارداری (تغییر رنگ دندان). حیوانات جوان <۴ ماه. بیماری کبدی شدید.',
    adverseEffects: 'GI upset, esophageal stricture (give with water/food), photosensitivity, tooth discoloration in young.',
    adverseEffectsFa: 'اختلال گوارش، تنگی مری (با آب/غذا بدهید)، تغییر رنگ دندان.',
    interactions: 'Antacids, iron, calcium reduce absorption. Warfarin: increased effect.',
    interactionsFa: 'آنتی‌اسیدها، آهن، کلسیم جذب را کاهش می‌دهند. وارفارین: افزایش اثر.',
    monitoring: 'Monitor for GI signs. Ensure adequate water intake to prevent esophageal irritation.',
    monitoringFa: 'پایش علائم گوارشی. تأمین مصرف آب کافی.',
    withdrawalPeriod: null,
    withdrawalPeriodFa: null,
    specialPopulations: 'Avoid in pregnant and young animals when possible. Follow with food and water.',
    specialPopulationsFa: 'اجتناب از حیوانات باردار و جوان در صورت امکان. با غذا و آب بدهید.',
    evidenceLevel: 'strong',
  },
  {
    id: 'drug_prednisolone',
    genericName: 'Prednisolone',
    genericNameFa: 'پریدنیزولون',
    drugClass: 'Glucocorticoid (corticosteroid)',
    drugClassFa: 'گلوکوکورتیکوئید (کورتیکواستروئید)',
    species: ['dog', 'cat', 'horse', 'other'],
    indication: 'Inflammatory conditions, autoimmune disease, allergies, immune-mediated disease, shock',
    indicationFa: 'بیماری‌های التهابی، خودایمنی، آلرژی، شوک',
    mechanism: 'Binds to glucocorticoid receptors, suppressing inflammatory and immune responses.',
    mechanismFa: 'اتصال به گیرنده‌های گلوکوکورتیکوئید، سرکوب التهاب و سیستم ایمنی.',
    doseMgPerKg: '0.5-2.0 mg/kg (anti-inflammatory); 2-4 mg/kg (immunosuppressive)',
    route: 'PO',
    routeFa: 'خوراکی',
    frequency: 'SID-BID (once to twice daily)',
    frequencyFa: 'یک تا دو بار در روز',
    duration: 'Taper gradually; varies by condition (days to months)',
    durationFa: 'تدریجی کاهش یابد؛ بسته به بیماری (روز تا ماه)',
    contraindications: 'Systemic fungal infections. GI ulcers. Diabetes. Do not stop abruptly after long-term use.',
    contraindicationsFa: 'عفونت‌های قارچی سیستمی. زخم گوارشی. دیابت. قطع ناگهانی ممنوع.',
    adverseEffects: 'PU/PD, polyphagia, weight gain, GI upset, immunosuppression, skin thinning, iatrogenic Cushing\'s.',
    adverseEffectsFa: 'افزایش ادرار/تشنگی، پراشتهایی، افزایش وزن، سرکوب ایمنی.',
    interactions: 'NSAIDs (GI ulcer risk), vaccines (reduced response), diuretics (hypokalemia).',
    interactionsFa: 'NSAIDها (خطر زخم)، واکسن‌ها (کاهش پاسخ)، دیورتیک‌ها.',
    monitoring: 'Monitor for signs of iatrogenic Cushing\'s, blood glucose, especially with long-term use.',
    monitoringFa: 'پایش علائم کوشینگ، قند خون، مخصوصاً در مصرف طولانی.',
    withdrawalPeriod: null,
    withdrawalPeriodFa: null,
    specialPopulations: 'Use with caution in diabetic, pregnant, or cardiac patients. Always taper.',
    specialPopulationsFa: 'احتیاط در دیابتی، باردار، یا قلبی. همیشه تدریجی قطع شود.',
    evidenceLevel: 'strong',
  },
  {
    id: 'drug_gabapentin',
    genericName: 'Gabapentin',
    genericNameFa: 'گاباپنتین',
    drugClass: 'Anticonvulsant / neuropathic pain modulator',
    drugClassFa: 'ضدتشنج / تعدیل‌کننده درد نوروپاتیک',
    species: ['dog', 'cat', 'horse', 'other'],
    indication: 'Neuropathic pain, seizures (adjunct), anxiety, chronic pain management',
    indicationFa: 'درد نوروپاتیک، تشنج (کمکی)، اضطراب، مدیریت درد مزمن',
    mechanism: 'Binds to alpha-2-delta subunit of voltage-gated calcium channels, modulating neurotransmitter release.',
    mechanismFa: 'اتصال به زیرواحد آلفا-۲-دلتای کانال‌های کلسیمی، تعدیل انتقال عصبی.',
    doseMgPerKg: '5-30 mg/kg (dogs/cats)',
    route: 'PO',
    routeFa: 'خوراکی',
    frequency: 'BID-TID (2-3 times daily)',
    frequencyFa: '۲-۳ بار در روز',
    duration: 'Long-term for chronic pain; varies for seizure management',
    durationFa: 'بلندمدت برای درد مزمن؛ متغیر برای تشنج',
    contraindications: 'Severe renal impairment (dose adjust). Abrupt discontinuation after long-term use.',
    contraindicationsFa: 'اختلال کلیوی شدید (تنظیم دوز). قطع ناگهانی بعد از مصرف طولانی.',
    adverseEffects: 'Sedation, ataxia (especially cats), weight gain. Usually mild and transient.',
    adverseEffectsFa: 'خواب‌آلودگی، آتاکسی (مخصوصاً گربه)، افزایش وزن. عموماً خفیف.',
    interactions: 'Antacids reduce absorption. Additive sedation with other CNS depressants.',
    interactionsFa: 'آنتی‌اسیدها جذب را کاهش می‌دهند. خواب‌آلودگی افزایشی با سایر سرکوب‌کننده‌های CNS.',
    monitoring: 'Monitor for sedation and ataxia. Assess pain response. Renal panel if long-term.',
    monitoringFa: 'پایش خواب‌آلودگی و آتاکسی. ارزیابی پاسخ درد.',
    withdrawalPeriod: null,
    withdrawalPeriodFa: null,
    specialPopulations: 'Dose reduce in renal impairment. Taper slowly if used long-term for seizures.',
    specialPopulationsFa: 'کاهش دوز در اختلال کلیوی. تدریجی قطع شود.',
    evidenceLevel: 'moderate',
  },
];
