import type { RedFlagDef } from '@/types';

export const redFlags: RedFlagDef[] = [
  {
    id: 'rf_respiratory_distress',
    fact: 'respiratory_distress',
    label: 'Respiratory distress',
    labelFa: 'تنگی نفس',
    message: 'Severe respiratory distress — immediate veterinary evaluation required.',
    messageFa: 'تنگی نفس شدید — ارزیابی فوری دامپزشکی ضروری است.',
    action: 'Transport to nearest veterinary emergency facility immediately.',
    actionFa: 'فوری حیوان را به نزدیک‌ترین کلینیک اورژانسی منتقل کنید.',
  },
  {
    id: 'rf_dyspnea',
    fact: 'dyspnea',
    label: 'Dyspnea (labored breathing)',
    labelFa: 'تنگی نفس شدید',
    message: 'Dyspnea is a life-threatening emergency.',
    messageFa: 'تنگی نفس شدید یک اورژانس خطرناک است.',
    action: 'Provide oxygen if possible and transport immediately.',
    actionFa: 'در صورت امکان اکسیژن بدهید و فوری منتقل کنید.',
  },
  {
    id: 'rf_seizures',
    fact: 'seizures',
    label: 'Seizures / Convulsions',
    labelFa: 'تشنج',
    message: 'Seizures require immediate veterinary evaluation.',
    messageFa: 'تشنج نیازمند ارزیابی فوری دامپزشکی است.',
    action: 'Keep the animal safe from injury, do not restrain, note duration, seek emergency care.',
    actionFa: 'حیوان را در جای امن بگذارید، محدود نکنید، زمان را ثبت کنید و فوری به دامپزشک ببرید.',
  },
  {
    id: 'rf_bloody_diarrhea',
    fact: 'bloody_diarrhea',
    label: 'Bloody diarrhea',
    labelFa: 'اسهال خونی',
    message: 'Bloody diarrhea may indicate parvovirus, hemorrhagic gastroenteritis, or intoxication.',
    messageFa: 'اسهال خونی می‌تواند نشانه پاروویروس یا مسمومیت باشد.',
    action: 'Seek veterinary care urgently, especially in young or unvaccinated animals.',
    actionFa: 'فوری به دامپزشک مراجعه کنید، به‌ویژه در حیوانات جوان یا واکسین‌نشده.',
  },
  {
    id: 'rf_hematemesis',
    fact: 'hematemesis',
    label: 'Vomiting blood',
    labelFa: 'استفراغ خونی',
    message: 'Hematemesis requires immediate evaluation.',
    messageFa: 'استفراغ خونی نیاز به ارزیابی فوری دارد.',
    action: 'Transport to veterinary emergency facility immediately.',
    actionFa: 'فوری حیوان را به کلینیک اورژانسی منتقل کنید.',
  },
  {
    id: 'rf_bloating',
    fact: 'bloating',
    label: 'Abdominal bloating',
    labelFa: 'نفخ شکم',
    message: 'Abdominal bloating in dogs may indicate GDV (gastric dilatation-volvulus) — a surgical emergency.',
    messageFa: 'نفخ شکم در سگ‌ها ممکن است نشانگر پیچ‌خوردگی معده باشد — اورژانس جراحی.',
    action: 'Do not allow food or water. Transport to emergency facility immediately.',
    actionFa: 'غذا و آب ندهید. فوری به اورژانس منتقل کنید.',
  },
  {
    id: 'rf_paralysis',
    fact: 'paralysis',
    label: 'Paralysis',
    labelFa: 'فلجی',
    message: 'Paralysis may indicate spinal injury or tick paralysis — urgent evaluation needed.',
    messageFa: 'فلجی ممکن است نشانه آسیت نخاعی باشد — ارزیابی فوری.',
    action: 'Keep the animal still and transport on a flat surface. Do not manipulate the spine.',
    actionFa: 'حیوان را بی‌حرکت نگه دارید و روی سطح صاف منتقل کنید.',
  },
  {
    id: 'rf_altered_mentation',
    fact: 'altered_mentation',
    label: 'Altered mental state',
    labelFa: 'تغییر سطح هوشیاری',
    message: 'Altered mentation requires immediate evaluation.',
    messageFa: 'تغییر هوشیاری نیازمند ارزیابی فوری است.',
    action: 'Transport to veterinary emergency facility immediately.',
    actionFa: 'فوری حیوان را به کلینیک اورژانسی منتقل کنید.',
  },
  {
    id: 'rf_urinary_blockage',
    fact: 'urinary_blockage',
    label: 'Urinary blockage',
    labelFa: 'انسداد ادراری',
    message: 'Urinary blockage is a life-threatening emergency, especially in male cats.',
    messageFa: 'انسداد ادراری یک اورژانس خطرناک است، به‌ویژه در گربه‌های نر.',
    action: 'Immediate veterinary care required. The bladder must be decompressed urgently.',
    actionFa: 'مراقبت فوری دامپزشکی ضروری است. مثانه باید فوری تخلیه شود.',
  },
  {
    id: 'rf_fracture',
    fact: 'fracture',
    label: 'Suspected fracture',
    labelFa: 'شکستگی مشکوک',
    message: 'Suspected fracture requires immobilization and urgent evaluation.',
    messageFa: 'شکستگی مشکوک نیازمند ثابت‌سازی و ارزیابی فوری است.',
    action: 'Immobilize the limb gently, transport to veterinary facility.',
    actionFa: 'اندام را با ملایمت ثابت کنید و به کلینیک منتقل کنید.',
  },
  {
    id: 'rf_toxin_exposure',
    fact: 'toxin_exposure',
    label: 'Known toxin exposure',
    labelFa: 'تماس با ماده سمی',
    message: 'Known toxin exposure — contact veterinarian or poison control immediately.',
    messageFa: 'تماس با ماده سمی — فوری با دامپزشک تماس بگیرید.',
    action: 'Bring the toxin container/package. Do not induce vomiting unless instructed.',
    actionFa: 'ظرف ماده سمی را بیاورید. استفراغ ندهید مگر با دستور.',
  },
  {
    id: 'rf_head_pressing',
    fact: 'head_pressing',
    label: 'Head pressing',
    labelFa: 'فشار دادن سر به دیوار',
    message: 'Head pressing indicates serious neurological disease — emergency.',
    messageFa: 'فشار دادن سر به دیوار نشان‌دهنده بیماری عصبی جدی است — اورژانس.',
    action: 'Transport to veterinary emergency facility immediately.',
    actionFa: 'فوری حیوان را به کلینیک اورژانسی منتقل کنید.',
  },
  {
    id: 'rf_glaucoma',
    fact: 'glaucoma_suspected',
    label: 'Suspected glaucoma',
    labelFa: 'گلوکوم مشکوک',
    message: 'Glaucoma can cause permanent blindness within hours — urgent ophthalmic evaluation.',
    messageFa: 'گلوکوم می‌تواند در چند ساعت باعث کوری دائمی شود — ارزیابی فوری.',
    action: 'Immediate veterinary evaluation needed to save vision.',
    actionFa: 'ارزیابی فوری دامپزشکی برای حفظ بینایی ضروری است.',
  },
];
