import type { Rule } from '@/types';

export const rules: Rule[] = [
  // ===== Canine Distemper =====
  {
    id: 'CD-001',
    name: 'Respiratory Distemper Pattern',
    description: 'Fever with respiratory signs in a dog',
    diseaseId: 'canine_distemper',
    conditions: [
      { fact: 'fever', operator: 'equals', value: true },
      { fact: 'cough', operator: 'equals', value: true },
      { fact: 'nasal_discharge', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'respiratory_syndrome_with_fever',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Fever combined with cough and nasal discharge suggests an infectious respiratory syndrome. In an incompletely vaccinated dog, distemper is a differential.',
    produces: ['respiratory_syndrome'],
  },
  {
    id: 'CD-002',
    name: 'Distemper with Neurological Signs',
    description: 'Respiratory signs plus neurological signs strongly support distemper',
    diseaseId: 'canine_distemper',
    conditions: [
      { fact: 'fever', operator: 'equals', value: true },
      { fact: 'cough', operator: 'equals', value: true },
      { fact: 'seizures', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'distemper_strongly_supported',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'The combination of fever, respiratory signs, and seizures is highly suspicious for canine distemper, especially with incomplete vaccination.',
    produces: ['distemper_neurologic'],
  },
  {
    id: 'CD-003',
    name: 'Distemper Risk Factor — Unvaccinated Young Dog',
    description: 'Incomplete vaccination in a young dog with fever and respiratory signs increases distemper likelihood',
    diseaseId: 'canine_distemper',
    conditions: [
      { fact: 'vaccination_incomplete', operator: 'equals', value: true },
      { fact: 'fever', operator: 'equals', value: true },
      { fact: 'cough', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'distemper_risk_amplified',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'An incompletely vaccinated dog with fever and cough has elevated risk for distemper. Vaccination status is a key epidemiological factor.',
  },
  {
    id: 'CD-004',
    name: 'Distemper — GI Signs',
    description: 'GI signs in addition to respiratory signs broaden the distemper picture',
    diseaseId: 'canine_distemper',
    conditions: [
      { fact: 'cough', operator: 'equals', value: true },
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'diarrhea', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'distemper_multisystem',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Distemper can affect multiple organ systems. Respiratory plus GI signs increase the breadth of the clinical picture.',
  },

  // ===== Canine Parvovirus =====
  {
    id: 'PV-001',
    name: 'Parvovirus Core Pattern',
    description: 'Bloody diarrhea with vomiting in a dog',
    diseaseId: 'canine_parvovirus',
    conditions: [
      { fact: 'bloody_diarrhea', operator: 'equals', value: true },
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'lethargy', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'parvovirus_suspected',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'The triad of bloody diarrhea, vomiting, and lethargy is the classic presentation of canine parvovirus enteritis.',
    produces: ['hemorrhagic_gastroenteritis'],
  },
  {
    id: 'PV-002',
    name: 'Parvovirus Risk — Unvaccinated Young Dog',
    description: 'Unvaccinated status in a young dog with GI signs strongly supports parvovirus',
    diseaseId: 'canine_parvovirus',
    conditions: [
      { fact: 'unvaccinated', operator: 'equals', value: true },
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'diarrhea', operator: 'equals', value: true },
      { fact: 'young_age', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'parvovirus_high_risk',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'An unvaccinated puppy with vomiting and diarrhea is at very high risk for parvovirus. This is a medical emergency.',
  },
  {
    id: 'PV-003',
    name: 'Parvovirus — Leukopenia',
    description: 'Leukopenia with GI signs supports parvovirus',
    diseaseId: 'canine_parvovirus',
    conditions: [
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'diarrhea', operator: 'equals', value: true },
      { fact: 'leukopenia', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'parvovirus_lab_supported',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Leukopenia in a dog with GI signs is highly supportive of parvovirus, as the virus destroys bone marrow precursors.',
  },

  // ===== Kennel Cough =====
  {
    id: 'KC-001',
    name: 'Kennel Cough Pattern',
    description: 'Dry cough with recent boarding history',
    diseaseId: 'kennel_cough',
    conditions: [
      { fact: 'dry_cough', operator: 'equals', value: true },
      { fact: 'recent_boarding', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'kennel_cough_likely',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'A dry/honking cough with recent boarding or multi-dog exposure is the classic presentation of kennel cough (infectious tracheobronchitis).',
  },
  {
    id: 'KC-002',
    name: 'Kennel Cough — Multi-pet Household',
    description: 'Dry cough in a multi-pet household',
    diseaseId: 'kennel_cough',
    conditions: [
      { fact: 'dry_cough', operator: 'equals', value: true },
      { fact: 'multi_pet_household', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'kennel_cough_likely',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Dry cough in a multi-pet household is consistent with infectious tracheobronchitis spread.',
  },

  // ===== Canine Influenza =====
  {
    id: 'CI-001',
    name: 'Canine Influenza Pattern',
    description: 'Moist cough with fever and nasal discharge',
    diseaseId: 'canine_influenza',
    conditions: [
      { fact: 'moist_cough', operator: 'equals', value: true },
      { fact: 'fever', operator: 'equals', value: true },
      { fact: 'nasal_discharge', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'influenza_suspected',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'A moist/productive cough with fever and nasal discharge is consistent with canine influenza, especially in group settings.',
  },

  // ===== Feline Panleukopenia =====
  {
    id: 'FP-001',
    name: 'Panleukopenia Core Pattern',
    description: 'Vomiting and diarrhea with fever in a cat',
    diseaseId: 'feline_panleukopenia',
    conditions: [
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'diarrhea', operator: 'equals', value: true },
      { fact: 'fever', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'panleukopenia_suspected',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Vomiting, diarrhea, and fever in a cat — especially unvaccinated — is highly suspicious for feline panleukopenia.',
    produces: ['feline_gastroenteritis'],
  },
  {
    id: 'FP-002',
    name: 'Panleukopenia — Unvaccinated Young Cat',
    description: 'Unvaccinated young cat with GI signs',
    diseaseId: 'feline_panleukopenia',
    conditions: [
      { fact: 'unvaccinated', operator: 'equals', value: true },
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'young_age', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'panleukopenia_high_risk',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'An unvaccinated kitten with vomiting is at very high risk for panleukopenia. This is a medical emergency.',
  },

  // ===== Feline URI =====
  {
    id: 'URI-001',
    name: 'Feline URI Pattern',
    description: 'Sneezing with nasal and ocular discharge in a cat',
    diseaseId: 'feline_uri',
    conditions: [
      { fact: 'sneezing', operator: 'equals', value: true },
      { fact: 'nasal_discharge', operator: 'equals', value: true },
      { fact: 'ocular_discharge', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'feline_uri_likely',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'The triad of sneezing, nasal discharge, and ocular discharge is the classic presentation of feline upper respiratory infection.',
  },
  {
    id: 'URI-002',
    name: 'Feline URI with Conjunctivitis',
    description: 'Sneezing with conjunctivitis in a cat',
    diseaseId: 'feline_uri',
    conditions: [
      { fact: 'sneezing', operator: 'equals', value: true },
      { fact: 'conjunctivitis', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'feline_uri_supported',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Sneezing with conjunctivitis is consistent with feline herpesvirus or calicivirus infection.',
  },

  // ===== Feline Urinary Tract Disease =====
  {
    id: 'UD-001',
    name: 'Feline Urinary Tract Disease',
    description: 'Straining to urinate with hematuria in a cat',
    diseaseId: 'feline_ud',
    conditions: [
      { fact: 'stranguria', operator: 'equals', value: true },
      { fact: 'hematuria', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'flutd_suspected',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'Straining to urinate with blood in the urine is the classic presentation of feline lower urinary tract disease.',
  },
  {
    id: 'UD-002',
    name: 'Urinary Blockage — Emergency',
    description: 'Unable to urinate is a life-threatening emergency',
    diseaseId: 'feline_ud',
    conditions: [
      { fact: 'urinary_blockage', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'urinary_blockage_emergency',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Urinary blockage is a life-threatening emergency, especially in male cats. Immediate decompression is required.',
  },

  // ===== GDV =====
  {
    id: 'GDV-001',
    name: 'GDV Pattern',
    description: 'Bloating with vomiting and weakness in a dog',
    diseaseId: 'gdv',
    conditions: [
      { fact: 'bloating', operator: 'equals', value: true },
      { fact: 'vomiting', operator: 'equals', value: true },
      { fact: 'lethargy', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'gdv_suspected_emergency',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Abdominal bloating with vomiting and lethargy in a dog is highly suspicious for gastric dilatation-volvulus. This is a surgical emergency.',
  },

  // ===== Flea Allergy Dermatitis =====
  {
    id: 'FAD-001',
    name: 'Flea Allergy Dermatitis Pattern',
    description: 'Itching with flea dirt present',
    diseaseId: 'flea_allergy_dermatitis',
    conditions: [
      { fact: 'pruritus', operator: 'equals', value: true },
      { fact: 'flea_dirt', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'flea_allergy_confirmed',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'Intense itching with visible flea dirt confirms flea allergy dermatitis.',
  },
  {
    id: 'FAD-002',
    name: 'Flea Allergy — Pruritus with Erythema',
    description: 'Itching with skin redness and alopecia',
    diseaseId: 'flea_allergy_dermatitis',
    conditions: [
      { fact: 'pruritus', operator: 'equals', value: true },
      { fact: 'erythema', operator: 'equals', value: true },
      { fact: 'alopecia', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'flea_allergy_likely',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Pruritus with erythema and alopecia is consistent with flea allergy dermatitis, even without visible flea dirt.',
  },

  // ===== Sarcoptic Mange =====
  {
    id: 'SM-001',
    name: 'Sarcoptic Mange Pattern',
    description: 'Intense itching with mange-type lesions and outdoor access',
    diseaseId: 'sarcoptic_mange',
    conditions: [
      { fact: 'pruritus', operator: 'equals', value: true },
      { fact: 'mange_lesions', operator: 'equals', value: true },
      { fact: 'outdoor_access', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'sarcoptic_mange_likely',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Intense pruritus with crusty lesions and outdoor access is consistent with sarcoptic mange. Skin scraping is needed for confirmation.',
  },

  // ===== Tick-Borne Disease =====
  {
    id: 'TBD-001',
    name: 'Tick-Borne Disease Pattern',
    description: 'Fever with tick exposure and lethargy',
    diseaseId: 'tick_borne_disease',
    conditions: [
      { fact: 'fever', operator: 'equals', value: true },
      { fact: 'tick_exposure', operator: 'equals', value: true },
      { fact: 'lethargy', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'tick_borne_suspected',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'Fever with known tick exposure and lethargy is consistent with a tick-borne disease such as ehrlichiosis or anaplasmosis.',
  },
  {
    id: 'TBD-002',
    name: 'Tick-Borne — Thrombocytopenia',
    description: 'Fever with low platelets and tick exposure',
    diseaseId: 'tick_borne_disease',
    conditions: [
      { fact: 'fever', operator: 'equals', value: true },
      { fact: 'thrombocytopenia', operator: 'equals', value: true },
      { fact: 'tick_exposure', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'tick_borne_lab_supported',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Fever with thrombocytopenia and tick exposure is strongly supportive of a tick-borne disease. 4Dx SNAP test recommended.',
  },

  // ===== Diabetes Mellitus =====
  {
    id: 'DM-001',
    name: 'Diabetes Mellitus Pattern',
    description: 'Polyuria and polydipsia with weight loss',
    diseaseId: 'diabetes_mellitus',
    conditions: [
      { fact: 'polyuria', operator: 'equals', value: true },
      { fact: 'polydipsia', operator: 'equals', value: true },
      { fact: 'weight_loss', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'diabetes_suspected',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'The classic triad of polyuria, polydipsia, and weight loss is highly suggestive of diabetes mellitus. Blood glucose and urinalysis needed.',
  },

  // ===== Chronic Kidney Disease =====
  {
    id: 'CKD-001',
    name: 'CKD Pattern',
    description: 'PU/PD with anorexia and weight loss',
    diseaseId: 'chronic_kidney_disease',
    conditions: [
      { fact: 'polyuria', operator: 'equals', value: true },
      { fact: 'polydipsia', operator: 'equals', value: true },
      { fact: 'anorexia', operator: 'equals', value: true },
      { fact: 'weight_loss', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'ckd_suspected',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'PU/PD with anorexia and weight loss is consistent with chronic kidney disease. Serum biochemistry and urinalysis are needed.',
  },
  {
    id: 'CKD-002',
    name: 'CKD — Azotemia',
    description: 'PU/PD with elevated kidney values confirms CKD suspicion',
    diseaseId: 'chronic_kidney_disease',
    conditions: [
      { fact: 'polyuria', operator: 'equals', value: true },
      { fact: 'polydipsia', operator: 'equals', value: true },
      { fact: 'azotemia', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'ckd_lab_supported',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'PU/PD with azotemia is strongly supportive of kidney disease. Urine specific gravity is needed to differentiate acute vs chronic.',
  },

  // ===== Hepatic Disease =====
  {
    id: 'HEP-001',
    name: 'Hepatic Disease Pattern',
    description: 'Jaundice with elevated liver enzymes',
    diseaseId: 'hepatic_disease',
    conditions: [
      { fact: 'jaundice', operator: 'equals', value: true },
      { fact: 'elevated_liver_enzymes', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'hepatic_disease_suspected',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Jaundice with elevated liver enzymes confirms hepatic dysfunction. Liver function tests and ultrasound are needed.',
  },
  {
    id: 'HEP-002',
    name: 'Hepatic Encephalopathy',
    description: 'Liver disease with altered mentation',
    diseaseId: 'hepatic_disease',
    conditions: [
      { fact: 'jaundice', operator: 'equals', value: true },
      { fact: 'altered_mentation', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'hepatic_encephalopathy_suspected',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Jaundice with altered mental status suggests hepatic encephalopathy — a serious complication of liver failure.',
  },

  // ===== Intoxication =====
  {
    id: 'TOX-001',
    name: 'Intoxication — Known Exposure',
    description: 'Known toxin exposure with GI or neurological signs',
    diseaseId: 'intoxication',
    conditions: [
      { fact: 'toxin_exposure', operator: 'equals', value: true },
      { fact: 'vomiting', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'intoxication_suspected',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Known toxin exposure with clinical signs confirms intoxicication. Contact poison control immediately. Bring the toxin container/package.',
  },
  {
    id: 'TOX-002',
    name: 'Intoxication — Neurological Signs',
    description: 'Toxin exposure with seizures or ataxia',
    diseaseId: 'intoxication',
    conditions: [
      { fact: 'toxin_exposure', operator: 'equals', value: true },
      { fact: 'seizures', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'intoxication_neurological_emergency',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Toxin exposure with seizures is a life-threatening emergency. Immediate veterinary care and poison control contact required.',
  },

  // ===== Congestive Heart Failure =====
  {
    id: 'CHF-001',
    name: 'CHF Pattern',
    description: 'Cough on exertion with exercise intolerance',
    diseaseId: 'chf',
    conditions: [
      { fact: 'cough_on_exertion', operator: 'equals', value: true },
      { fact: 'exercise_intolerance', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'chf_suspected',
    evidenceLevel: 'moderate',
    priority: 'medium',
    explanation: 'Cough on exertion with exercise intolerance is consistent with congestive heart failure. Thoracic radiographs and echocardiography needed.',
  },
  {
    id: 'CHF-002',
    name: 'CHF — Respiratory Distress',
    description: 'CHF signs with respiratory distress indicates decompensation',
    diseaseId: 'chf',
    conditions: [
      { fact: 'exercise_intolerance', operator: 'equals', value: true },
      { fact: 'dyspnea', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'chf_decompensated',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Exercise intolerance with dyspnea suggests decompensated heart failure with possible pulmonary edema. Emergency care required.',
  },

  // ===== IVDD =====
  {
    id: 'IVDD-001',
    name: 'IVDD Pattern',
    description: 'Back pain with paresis in a dog',
    diseaseId: 'ivdd',
    conditions: [
      { fact: 'back_pain', operator: 'equals', value: true },
      { fact: 'paresis', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'ivdd_suspected',
    evidenceLevel: 'strong',
    priority: 'medium',
    explanation: 'Back pain with paresis is the classic presentation of intervertebral disc disease. Neurological examination and imaging are needed.',
  },
  {
    id: 'IVDD-002',
    name: 'IVDD — Paralysis',
    description: 'Back pain with paralysis is a surgical emergency',
    diseaseId: 'ivdd',
    conditions: [
      { fact: 'back_pain', operator: 'equals', value: true },
      { fact: 'paralysis', operator: 'equals', value: true },
    ],
    conditionLogic: 'AND',
    conclusion: 'ivdd_surgical_emergency',
    evidenceLevel: 'strong',
    priority: 'high',
    explanation: 'Back pain with paralysis indicates severe spinal cord compression. This is a potential surgical emergency — time is critical.',
  },
];

// Required tests for each disease
export const diseaseRequiredTests: Record<string, { label: string; labelFa: string }[]> = {
  canine_distemper: [
    { label: 'PCR testing (respiratory/conjunctival swab)', labelFa: 'آزمایش PCR (سواپ تنفسی/ملتحمه)' },
    { label: 'CBC (for leukopenia)', labelFa: 'شمارش گلبول خونی (برای leukopenia)' },
    { label: 'Neurological examination', labelFa: 'معاینه عصبی' },
    { label: 'Vaccination history verification', labelFa: 'بررسی سوابق واکسیناسیون' },
  ],
  canine_parvovirus: [
    { label: 'SNAP Parvo antigen test (fecal)', labelFa: 'آزمایش آنتی‌ژن پاروویروس (مدفوع)' },
    { label: 'CBC (for leukopenia)', labelFa: 'شمارش گلبول خونی' },
    { label: 'Electrolytes and acid-base', labelFa: 'الکترولیت‌ها و اسید-باز' },
    { label: 'Abdominal imaging if needed', labelFa: 'تصویربرداری شکمی در صورت نیاز' },
  ],
  kennel_cough: [
    { label: 'Clinical examination', labelFa: 'معاینه بالینی' },
    { label: 'Thoracic radiographs if complicated', labelFa: 'رادیوگرافی قفسه سینه در صورت عارضه' },
    { label: 'Bacterial culture if persistent', labelFa: 'کشت باکتریایی در صورت استمرار' },
  ],
  canine_influenza: [
    { label: 'PCR testing (nasal/pharyngeal swab)', labelFa: 'آزمایش PCR (سواب بینی/حلق)' },
    { label: 'Serology (paired titers)', labelFa: 'سرولوژی (تیتر جفتی)' },
    { label: 'Thoracic radiographs', labelFa: 'رادیوگرافی قفسه سینه' },
  ],
  feline_panleukopenia: [
    { label: 'SNAP Parvo antigen test (fecal)', labelFa: 'آزمایش آنتی‌ژن پاروویروس (مدفوع)' },
    { label: 'CBC (for leukopenia)', labelFa: 'شمارش گلبول خونی' },
    { label: 'Electrolytes and acid-base', labelFa: 'الکترولیت‌ها و اسید-باز' },
  ],
  feline_uri: [
    { label: 'Clinical examination', labelFa: 'معاینه بالینی' },
    { label: 'PCR for herpesvirus/calicivirus', labelFa: 'PCR برای هرپس/کالسی‌ویروس' },
    { label: 'Eye examination for corneal ulcers', labelFa: 'معاینه چشم برای زخم قرنیه' },
  ],
  feline_ud: [
    { label: 'Urinalysis + culture', labelFa: 'آنالیز ادرار + کشت' },
    { label: 'Abdominal ultrasound', labelFa: 'سونوگرافی شکم' },
    { label: 'Blood work (BUN/creatinine)', labelFa: 'آزمایش خون (BUN/کراتینین)' },
  ],
  gdv: [
    { label: 'Abdominal radiographs (right lateral)', labelFa: 'رادیوگرافی شکم (بغل راست)' },
    { label: 'Emergency blood work', labelFa: 'آزمایش خون اورژانسی' },
    { label: 'ECG', labelFa: 'نوار قلب' },
  ],
  flea_allergy_dermatitis: [
    { label: 'Flea comb examination', labelFa: 'بررسی با شانه کک' },
    { label: 'Skin scrapings to rule out mites', labelFa: 'خراش پوست برای رد کردن کنه' },
    { label: 'Intradermal allergy testing', labelFa: 'آزمایش آلرژی داخل‌پوستی' },
  ],
  sarcoptic_mange: [
    { label: 'Skin scrapings (multiple sites)', labelFa: 'خراش پوست (چند ناحیه)' },
    { label: 'Response to treatment trial', labelFa: 'پاسخ به درمان آزمایشی' },
  ],
  tick_borne_disease: [
    { label: '4Dx SNAP test', labelFa: 'آزمایش 4Dx SNAP' },
    { label: 'CBC with platelet count', labelFa: 'شمارش گلبول با پلاکت' },
    { label: 'Blood smear for organisms', labelFa: 'اسمیر خون برای موجودات' },
  ],
  diabetes_mellitus: [
    { label: 'Blood glucose (fasting)', labelFa: 'قند خون ناشتا' },
    { label: 'Urinalysis (for glucose/ketones)', labelFa: 'آنالیز ادرار (قند/کتون)' },
    { label: 'Fructosamine', labelFa: 'فروکتوزآمین' },
  ],
  chronic_kidney_disease: [
    { label: 'Serum biochemistry (BUN/Cre)', labelFa: 'بیوشیمی سرم (BUN/کراتینین)' },
    { label: 'Urinalysis + USG', labelFa: 'آنالیز ادرار + USG' },
    { label: 'Abdominal ultrasound', labelFa: 'سونوگرافی شکم' },
    { label: 'Blood pressure', labelFa: 'فشار خون' },
  ],
  hepatic_disease: [
    { label: 'Liver panel (ALT, ALP, GGT, Bili)', labelFa: 'پنل کبدی (ALT, ALP, GGT, Bili)' },
    { label: 'Bile acids assay', labelFa: 'آزمایش اسید صفراوی' },
    { label: 'Abdominal ultrasound', labelFa: 'سونوگرافی شکم' },
    { label: 'Coagulation profile', labelFa: 'پروفایل انعقادی' },
  ],
  intoxication: [
    { label: 'Identify the toxin (bring container)', labelFa: 'شناسایی ماده سمی (ظرف را بیاورید)' },
    { label: 'Baseline blood work', labelFa: 'آزمایش خون پایه' },
    { label: 'Call poison control', labelFa: 'تماس با مرکز مسمومیت' },
  ],
  chf: [
    { label: 'Thoracic radiographs', labelFa: 'رادیوگرافی قفسه سینه' },
    { label: 'Echocardiography', labelFa: 'اکوکاردیوگرافی' },
    { label: 'NT-proBNP', labelFa: 'NT-proBNP' },
  ],
  ivdd: [
    { label: 'Neurological examination + localization', labelFa: 'معاینه عصبی + محلی‌سازی' },
    { label: 'Spinal radiographs', labelFa: 'رادیوگرافی ستون فقرات' },
    { label: 'MRI or CT + myelography', labelFa: 'MRI یا CT + مایلوگرافی' },
  ],
};
