import type { SampleCase } from '@/types';

export const sampleCases: SampleCase[] = [
  {
    id: 'case_001',
    title: 'Unvaccinated Puppy with Bloody Diarrhea',
    titleFa: 'سگ‌های جوان واکسین‌نشده با اسهال خونی',
    description: 'A 4-month-old unvaccinated puppy presents with vomiting, bloody diarrhea, and lethargy for 2 days.',
    descriptionFa: 'یک سگ ۴ ماهه واکسین‌نشده با استفراغ، اسهال خونی و بی‌حالی به مدت ۲ روز.',
    input: {
      species: 'dog',
      ageYears: 0.3,
      sex: 'male',
      signs: {
        vomiting: true,
        bloody_diarrhea: true,
        lethargy: true,
        anorexia: true,
        fever: true,
        dehydration: true,
        abdominal_pain: true,
      },
      vaccinationStatus: 'incomplete',
      durationDays: 2,
    },
  },
  {
    id: 'case_002',
    title: 'Cat with Sneezing and Ocular Discharge',
    titleFa: 'گربه با عطسه و ترشح چشم',
    description: 'A 2-year-old cat from a multi-cat household with sneezing, nasal and ocular discharge for 5 days.',
    descriptionFa: 'یک گربه ۲ ساله از خانه‌ای با چند گربه، با عطسه، ترشح بینی و چشم به مدت ۵ روز.',
    input: {
      species: 'cat',
      ageYears: 2,
      sex: 'female',
      signs: {
        sneezing: true,
        nasal_discharge: true,
        ocular_discharge: true,
        conjunctivitis: true,
        lethargy: true,
        anorexia: true,
        fever: true,
      },
      vaccinationStatus: 'incomplete',
      environmentalFactors: ['multi_cat_household'],
      durationDays: 5,
    },
  },
  {
    id: 'case_003',
    title: 'Dog with Dry Cough After Boarding',
    titleFa: 'سگ با سرفه خشک پس از هتل حیوانات',
    description: 'A 3-year-old vaccinated dog developed a dry honking cough 3 days after boarding.',
    descriptionFa: 'یک سگ ۳ ساله واکسینه که ۳ روز پس از اقامت در هتل حیوانات، سرفه خشک پیدا کرد.',
    input: {
      species: 'dog',
      ageYears: 3,
      sex: 'male',
      signs: {
        dry_cough: true,
        sneezing: true,
        nasal_discharge: true,
      },
      vaccinationStatus: 'complete',
      environmentalFactors: ['recent_boarding'],
      durationDays: 3,
    },
  },
  {
    id: 'case_004',
    title: 'Dog with Fever, Cough, and Seizures',
    titleFa: 'سگ با تب، سرفه و تشنج',
    description: 'A 6-month-old incompletely vaccinated puppy with fever, cough, nasal discharge, and recent onset seizures.',
    descriptionFa: 'یک سگ ۶ ماهه با واکسیناسیون ناقص، تب، سرفه، ترشح بینی و شروع اخیری تشنج.',
    input: {
      species: 'dog',
      ageYears: 0.5,
      sex: 'female',
      signs: {
        fever: true,
        cough: true,
        nasal_discharge: true,
        ocular_discharge: true,
        seizures: true,
        ataxia: true,
        lethargy: true,
        anorexia: true,
      },
      vaccinationStatus: 'incomplete',
      durationDays: 7,
    },
  },
  {
    id: 'case_005',
    title: 'Cat Straining to Urinate',
    titleFa: 'گربه با مشکل ادرار کردن',
    description: 'A 4-year-old male cat straining to urinate with blood in urine for 1 day.',
    descriptionFa: 'یک گربه ۴ ساله نر که مشکل ادرار کردن دارد و خون در ادرارش دیده شده به مدت ۱ روز.',
    input: {
      species: 'cat',
      ageYears: 4,
      sex: 'male',
      signs: {
        stranguria: true,
        hematuria: true,
        abdominal_pain: true,
        lethargy: true,
      },
      durationDays: 1,
    },
  },
  {
    id: 'case_006',
    title: 'Dog with Itching and Flea Dirt',
    titleFa: 'سگ با خارش و فضله کک',
    description: 'A 5-year-old dog with intense itching, hair loss, skin redness, and visible flea dirt.',
    descriptionFa: 'یک سگ ۵ ساله با خارش شدید، ریزش مو، قرمزی پوست و فضله کک قابل مشاهده.',
    input: {
      species: 'dog',
      ageYears: 5,
      signs: {
        pruritus: true,
        alopecia: true,
        erythema: true,
        flea_dirt: true,
        skin_lesions: true,
      },
      durationDays: 14,
    },
  },
  {
    id: 'case_007',
    title: 'Dog with Fever and Tick Exposure',
    titleFa: 'سگ با تب و تماس با کنه',
    description: 'A 4-year-old dog with fever, lethargy, lameness, and known tick exposure.',
    descriptionFa: 'یک سگ ۴ ساله با تب، بی‌حالی، لنگی و سابقه تماس با کنه.',
    input: {
      species: 'dog',
      ageYears: 4,
      signs: {
        fever: true,
        lethargy: true,
        anorexia: true,
        lameness: true,
        joint_swelling: true,
        lymphadenopathy: true,
      },
      environmentalFactors: ['tick_exposure'],
      labFindings: {
        thrombocytopenia: true,
      },
      durationDays: 5,
    },
  },
  {
    id: 'case_008',
    title: 'Cat with PU/PD and Weight Loss',
    titleFa: 'گربه با تکرر ادرار، تشنگی و کاهش وزن',
    description: 'An 8-year-old cat with excessive drinking, urination, and weight loss over a month.',
    descriptionFa: 'یک گربه ۸ ساله با تشنگی زیاد، تکرر ادرار و کاهش وزن طی یک ماه.',
    input: {
      species: 'cat',
      ageYears: 8,
      signs: {
        polyuria: true,
        polydipsia: true,
        weight_loss: true,
        lethargy: true,
      },
      durationDays: 30,
    },
  },
];
