import type { VaccinationSchedule } from '@/types';

export const vaccinationSchedules: VaccinationSchedule[] = [
  // Dog
  {
    id: 'vac_dog_dhpp',
    species: 'dog',
    disease: 'Distemper, Hepatitis, Parvovirus, Parainfluenza',
    diseaseFa: 'دستمپ، هپاتیت، پاروویروس، پاراآنفلوآنزا',
    vaccineName: 'DHPP (DAPP)',
    vaccineNameFa: 'واکسن DHPP',
    ageFirstDose: '6-8 weeks',
    boosterInterval: '3-4 weeks apart, 3 doses',
    revaccination: 'Annual or triennial (per manufacturer)',
    notes: 'Core vaccine. Puppies need a series starting at 6-8 weeks, ending at 16 weeks.',
    notesFa: 'واکسن پایه. توله‌سگ‌ها نیاز به سری واکسیناسیون از ۶-۸ هفته تا ۱۶ هفته دارند.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_dog_rabies',
    species: 'dog',
    disease: 'Rabies',
    diseaseFa: 'هاری',
    vaccineName: 'Rabies',
    vaccineNameFa: 'واکسن هاری',
    ageFirstDose: '12-16 weeks',
    boosterInterval: 'Single dose',
    revaccination: 'Annual or triennial (per local regulations and product label)',
    notes: 'Required by law in many jurisdictions. Follow local regulations for schedule.',
    notesFa: 'در بسیاری از مناطق الزامی است. طبق قوانین محلی عمل کنید.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_dog_bordetella',
    species: 'dog',
    disease: 'Bordetella (Kennel Cough)',
    diseaseFa: 'بوردتلا (سرفه لانه)',
    vaccineName: 'Bordetella',
    vaccineNameFa: 'واکسن بوردتلا',
    ageFirstDose: '8 weeks',
    boosterInterval: 'Single dose (intranasal) or 2 doses (injectable)',
    revaccination: 'Annual',
    notes: 'Non-core vaccine. Recommended for dogs that board, show, or are in multi-dog environments.',
    notesFa: 'واکسن غیرپایه. برای سگ‌هایی که در محیط‌های چندسگی هستند توصیه می‌شود.',
    evidenceLevel: 'moderate',
  },
  {
    id: 'vac_dog_leptospirosis',
    species: 'dog',
    disease: 'Leptospirosis',
    diseaseFa: 'لپتوسپیروز',
    vaccineName: 'Leptospirosis (4-way)',
    vaccineNameFa: 'واکسن لپتوسپیروز',
    ageFirstDose: '12 weeks',
    boosterInterval: '2 doses, 3-4 weeks apart',
    revaccination: 'Annual',
    notes: 'Non-core. Recommended in endemic areas or for dogs with outdoor exposure to wildlife/standing water.',
    notesFa: 'غیرپایه. در مناطق بومی یا سگ‌های با تماس فضای باز توصیه می‌شود.',
    evidenceLevel: 'moderate',
  },

  // Cat
  {
    id: 'vac_cat_fvrcp',
    species: 'cat',
    disease: 'Feline Viral Rhinotracheitis, Calicivirus, Panleukopenia',
    diseaseFa: 'رینوتراکئیت ویروسی، کالیسی‌ویروس، پانلوکوپنی',
    vaccineName: 'FVRCP',
    vaccineNameFa: 'واکسن FVRCP',
    ageFirstDose: '6-8 weeks',
    boosterInterval: '3-4 weeks apart, 3 doses',
    revaccination: 'Annual or triennial (per manufacturer and risk assessment)',
    notes: 'Core vaccine for all cats. Kittens need series ending at 16 weeks.',
    notesFa: 'واکسن پایه برای همه گربه‌ها. گربه‌چه‌ها نیاز به سری کامل تا ۱۶ هفته دارند.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_cat_rabies',
    species: 'cat',
    disease: 'Rabies',
    diseaseFa: 'هاری',
    vaccineName: 'Rabies',
    vaccineNameFa: 'واکسن هاری',
    ageFirstDose: '12-16 weeks',
    boosterInterval: 'Single dose',
    revaccination: 'Annual or triennial (per local regulations)',
    notes: 'Core vaccine. Required by law in many jurisdictions.',
    notesFa: 'واکسن پایه. در بسیاری از مناطق الزامی است.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_cat_feLV',
    species: 'cat',
    disease: 'Feline Leukemia Virus',
    diseaseFa: 'ویروس لوسمی گربه',
    vaccineName: 'FeLV',
    vaccineNameFa: 'واکسن FeLV',
    ageFirstDose: '8 weeks',
    boosterInterval: '2 doses, 3-4 weeks apart',
    revaccination: 'Annual (for at-risk cats only)',
    notes: 'Non-core. Recommended for kittens and cats with outdoor access. Test before vaccination.',
    notesFa: 'غیرپایه. برای گربه‌های دارای دسترسی به بیرون توصیه می‌شود. قبل از واکسیناسیون تست شود.',
    evidenceLevel: 'moderate',
  },

  // Horse
  {
    id: 'vac_horse_eewh',
    species: 'horse',
    disease: 'Eastern/Western Equine Encephalomyelitis, West Nile Virus',
    diseaseFa: 'آنسیفالومایلیت شرقی/غربی، ویروس نیل غربی',
    vaccineName: 'EEE/WEE/WNV',
    vaccineNameFa: 'واکسن EEE/WEE/WNV',
    ageFirstDose: '4-6 months',
    boosterInterval: '2 doses, 4-6 weeks apart',
    revaccination: 'Annual (spring, before mosquito season)',
    notes: 'Core vaccine. Timing should precede mosquito season by 4-6 weeks.',
    notesFa: 'واکسن پایه. ۴-۶ هفته قبل از فصل پشه اجرا شود.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_horse_tetanus',
    species: 'horse',
    disease: 'Tetanus',
    diseaseFa: 'کزاز',
    vaccineName: 'Tetanus Toxoid',
    vaccineNameFa: 'واکسن کزاز',
    ageFirstDose: '4-6 months',
    boosterInterval: '2 doses, 4-6 weeks apart',
    revaccination: 'Annual',
    notes: 'Core vaccine. Horses are highly susceptible to tetanus. Booster after wounds if >6 months.',
    notesFa: 'واکسن پایه. اسب‌ها به کزاز حساس هستند. در صورت زخم، یادآور لازم است.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_horse_influenza',
    species: 'horse',
    disease: 'Equine Influenza',
    diseaseFa: 'آنفلوآنزا اسبی',
    vaccineName: 'Equine Influenza',
    vaccineNameFa: 'واکسن آنفلوآنزا اسبی',
    ageFirstDose: '6 months',
    boosterInterval: '2-3 doses, 4 weeks apart',
    revaccination: 'Semi-annual to annual (depending on risk)',
    notes: 'Core for performance/show horses. Bi-annual for high-exposure horses.',
    notesFa: 'پایه برای اسب‌های مسابقه‌ای. سالی دو بار برای اسب‌های در معرض تماس بالا.',
    evidenceLevel: 'strong',
  },

  // Cattle
  {
    id: 'vac_cattle_brucellosis',
    species: 'cattle',
    disease: 'Brucellosis',
    diseaseFa: 'بروسلوز',
    vaccineName: 'Brucella abortus RB51',
    vaccineNameFa: 'واکسن بروسلا RB51',
    ageFirstDose: '4-12 months (heifers)',
    boosterInterval: 'Single dose',
    revaccination: 'Not typically revaccinated',
    notes: 'Follow national/regional regulations. Official calfhood vaccination.',
    notesFa: 'طبق مقررات ملی/منطقه‌ای عمل کنید. واکسیناسیون دوران گوگالی رسمی.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_cattle_bvd',
    species: 'cattle',
    disease: 'Bovine Viral Diarrhea',
    diseaseFa: 'اسهال ویروسی گاو',
    vaccineName: 'BVD',
    vaccineNameFa: 'واکسن BVD',
    ageFirstDose: '4-6 months',
    boosterInterval: '2 doses, 3-4 weeks apart',
    revaccination: 'Annual',
    notes: 'Core herd health. Modify based on herd status (PI testing recommended).',
    notesFa: 'پایه سلامت گله. بر اساس وضعیت گله تنظیم شود.',
    evidenceLevel: 'moderate',
  },

  // Sheep/Goat
  {
    id: 'vac_sheep_clostridial',
    species: 'sheep',
    disease: 'Clostridial Diseases (CDT)',
    diseaseFa: 'بیماری‌های کلستریدیومی (CDT)',
    vaccineName: 'CDT (Clostridium perfringens C&D + Tetanus)',
    vaccineNameFa: 'واکسن CDT',
    ageFirstDose: '4-8 weeks',
    boosterInterval: '2 doses, 4 weeks apart',
    revaccination: 'Annual (pre-lambing for ewes)',
    notes: 'Core vaccine for sheep. Pregnant ewes should be boosted 4 weeks before lambing.',
    notesFa: 'واکسن پایه. میش‌های باردار ۴ هفته قبل از زایمان یادآور بزنند.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_goat_clostridial',
    species: 'goat',
    disease: 'Clostridial Diseases (CDT)',
    diseaseFa: 'بیماری‌های کلستریدیومی (CDT)',
    vaccineName: 'CDT',
    vaccineNameFa: 'واکسن CDT',
    ageFirstDose: '4-8 weeks',
    boosterInterval: '2 doses, 4 weeks apart',
    revaccination: 'Annual',
    notes: 'Core vaccine for goats. Follow same protocol as sheep.',
    notesFa: 'واکسن پایه برای بز. مانند گوسفند اجرا شود.',
    evidenceLevel: 'strong',
  },

  // Poultry
  {
    id: 'vac_chicken_nd',
    species: 'chicken',
    disease: 'Newcastle Disease',
    diseaseFa: 'بیماری نیوکاسل',
    vaccineName: 'Newcastle Disease (La Sota or Hitchner B1)',
    vaccineNameFa: 'واکسن نیوکاسل',
    ageFirstDose: 'Day 1 (spray/eye drop) or 7-10 days (water)',
    boosterInterval: 'Varies by program',
    revaccination: 'Every 6-8 weeks (layer/breeder flocks)',
    notes: 'Core vaccine. Follow local regulations and flock-specific program.',
    notesFa: 'واکسن پایه. طبق مقررات محلی و برنامه گله اجرا شود.',
    evidenceLevel: 'strong',
  },
  {
    id: 'vac_chicken_ib',
    species: 'chicken',
    disease: 'Infectious Bronchitis',
    diseaseFa: 'برونشیت عفونی',
    vaccineName: 'IB (Massachusetts type)',
    vaccineNameFa: 'واکسن IB',
    ageFirstDose: 'Day 1 (spray) or 7-10 days (water)',
    boosterInterval: 'Varies by program',
    revaccination: 'As needed per flock program',
    notes: 'Often combined with Newcastle. Follow flock veterinarian program.',
    notesFa: 'اغلب با نیوکاسل ترکیب می‌شود. طبق برنامه دامپزشک گله اجرا شود.',
    evidenceLevel: 'moderate',
  },
];
